name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: sudo apt-get update && sudo apt-get install -y --fix-missing shellcheck

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "shellcheck"
        run: test/shellcheck

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          - debian:13
          - fedora:42
          - fedora:43
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Disable AppArmor
        run: |
          sudo systemctl disable --now apparmor || true
          sudo aa-teardown || true

      - name: "Run tests"
        run: test/run -c -s ${{ matrix.server }}

  distro:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian:13
          - fedora:42
          - fedora:43
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Run tests"
        run: test/run -c -d ${{ matrix.distro }}
